---
title: "Trabajo-2"
output: html_document
---

## Parte 2 — Introducción a R

```{r}
# Usar el dataset ya importado en el entorno
df <- epa_http

# Renombrar columnas
names(df) <- c("host", "time", "method", "path", "protocol", "status", "bytes")

# Limpiar campos
df$time <- gsub("^\$begin:math:display$\|\\$end:math:display$$", "", df$time)      # quitar corchetes []
df$method <- gsub('"', "", df$method)          # quitar comillas de GET
df$protocol <- gsub('"', "", df$protocol)      # quitar comillas de HTTP/1.0

# Convertir tipos
df$status <- as.numeric(df$status)
df$bytes[df$bytes == "-"] <- NA
df$bytes <- as.numeric(df$bytes)

head(df)
str(df)
summary(df)



# Extraer hora desde el campo time
df$hour <- as.numeric(sapply(strsplit(df$time, ":"), function(x) x[2]))

dim(df)

media_bytes <- mean(df$bytes, na.rm = TRUE)
media_bytes

edu_idx <- grepl("\\.edu$", df$host)

total_edu <- sum(edu_idx, na.rm = TRUE)
hosts_edu_unicos <- length(unique(df$host[edu_idx]))
hosts_edu_repetidos <- total_edu - hosts_edu_unicos

total_edu
hosts_edu_unicos
hosts_edu_repetidos